version: "3.9"

networks:
  app_pathway_network:
    external: true
    
services:
    smsd:
      container_name: smsd
      build:
        dockerfile: $DOCKERFILE
        context: $CONTEXT
      env_file:
        - $RUNTIME_ENV 
      volumes:
        # apppathway pkgs
        - $ROOT/pkg/errors:$ROOT/pkg/errors
        - $ROOT/pkg/debug:$ROOT/pkg/debug
        # this service
        - $MAIN/pkg/plugins/sms/cmd/smsd/devstart/run:$MAIN/pkg/plugins/sms/run
        - $MAIN/pkg/plugins/sms:$MAIN/pkg/plugins/sms
        # env
        - $MAIN/config/dev/secrets/crt/auth:/etc/ssl/certs/auth
        - $MAIN/config/dev/secrets/crt/dgraph:/etc/ssl/certs/dgraph
      networks:
        app_pathway_network: