#!/bin/bash 
ROOT=/workspaces/devspirit
DEV=${ROOT}/examples/prodapi/config/dev
DOCKER_IGNORE=${ROOT}/.dockerignore 

SERVICE=is 
UP_FLAGS=$1 
SERVICE_IGNORES=$DEV/is/.dockerignore DOCKER_COMPOSE=$DEV/is/docker-compose.yml  

sudo cat $SERVICE_IGNORES > $DOCKER_IGNORE 
sudo docker-compose -f $DOCKER_COMPOSE up $UP_FLAGS $SERVICE 
