
# cli build
isb: 
	is/up --build
# cli up
is: 
	is/up 

# intent-system deamon build
idb: 
	intentsysd/up --build

# intent-system deamon up
id: 
	intentsysd/up 

# intent build
inb: 
	intentd/up --build
	
# intent up
in: 
	intentd/up 
	
# scheduler build
schb: 
	schedulerd/up --build

# scheduler up
sch: 
	schedulerd/up

# # sms build
smsb: 
	smsd/up --build

# sms up
sms: 
	smsd/up 

	

