// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: crud_basic.proto

package crudbasicpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhenomenaClient is the client API for Phenomena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhenomenaClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Phenomenon(ctx context.Context, in *PhenomenonRequest, opts ...grpc.CallOption) (*PhenomenonResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type phenomenaClient struct {
	cc grpc.ClientConnInterface
}

func NewPhenomenaClient(cc grpc.ClientConnInterface) PhenomenaClient {
	return &phenomenaClient{cc}
}

func (c *phenomenaClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/crudbasicpb.Phenomena/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phenomenaClient) Phenomenon(ctx context.Context, in *PhenomenonRequest, opts ...grpc.CallOption) (*PhenomenonResponse, error) {
	out := new(PhenomenonResponse)
	err := c.cc.Invoke(ctx, "/crudbasicpb.Phenomena/Phenomenon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phenomenaClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/crudbasicpb.Phenomena/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phenomenaClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/crudbasicpb.Phenomena/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhenomenaServer is the server API for Phenomena service.
// All implementations should embed UnimplementedPhenomenaServer
// for forward compatibility
type PhenomenaServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Phenomenon(context.Context, *PhenomenonRequest) (*PhenomenonResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedPhenomenaServer should be embedded to have forward compatible implementations.
type UnimplementedPhenomenaServer struct {
}

func (UnimplementedPhenomenaServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPhenomenaServer) Phenomenon(context.Context, *PhenomenonRequest) (*PhenomenonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Phenomenon not implemented")
}
func (UnimplementedPhenomenaServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPhenomenaServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

// UnsafePhenomenaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhenomenaServer will
// result in compilation errors.
type UnsafePhenomenaServer interface {
	mustEmbedUnimplementedPhenomenaServer()
}

func RegisterPhenomenaServer(s grpc.ServiceRegistrar, srv PhenomenaServer) {
	s.RegisterService(&Phenomena_ServiceDesc, srv)
}

func _Phenomena_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhenomenaServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crudbasicpb.Phenomena/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhenomenaServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phenomena_Phenomenon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhenomenonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhenomenaServer).Phenomenon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crudbasicpb.Phenomena/Phenomenon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhenomenaServer).Phenomenon(ctx, req.(*PhenomenonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phenomena_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhenomenaServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crudbasicpb.Phenomena/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhenomenaServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Phenomena_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhenomenaServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crudbasicpb.Phenomena/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhenomenaServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Phenomena_ServiceDesc is the grpc.ServiceDesc for Phenomena service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Phenomena_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crudbasicpb.Phenomena",
	HandlerType: (*PhenomenaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Phenomena_Create_Handler,
		},
		{
			MethodName: "Phenomenon",
			Handler:    _Phenomena_Phenomenon_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Phenomena_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Phenomena_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crud_basic.proto",
}
