#!/bin/bash
ROOT=/home/nate/code/app-pathway
DEV=${ROOT}/examples/prodapi/config/dev
DOCKER_IGNORE=${ROOT}/.dockerignore 

SERVICE=intentd 
UP_FLAGS=$1 
SERVICE_IGNORES=${DEV}/intentd/.dockerignore 
DOCKER_COMPOSE=${DEV}/intentd/docker-compose.yml 

sudo cat ${SERVICE_IGNORES} > ${DOCKER_IGNORE} 
sudo docker-compose -f ${DOCKER_COMPOSE} up ${UP_FLAGS} ${SERVICE} 
