version: "3.9"

networks:
  app_pathway_network:
    external: true
    
services:
    behaviord:
      restart: always
      container_name: behaviord
      build:
        dockerfile: pkg/user/behavior/build/package/Dockerfile
        context: ../../../
      env_file:
        - env/behavior.env   
      volumes:
        - $PKG/user/behavior/cmd/behaviord/devstart/run:$PKG/user/behavior/run
        - $PKG/user/behavior:$PKG/user/behavior
        - $PKG/user:$PKG/user
        - $PKG/net:$PKG/net
        - $PKG/errors:$PKG/errors
        - $PKG/debug:$PKG/debug
        - $ROOT/secrets/crt/auth:/etc/ssl/certs/auth
        - $ROOT/secrets/crt/dgraph:/etc/ssl/certs/dgraph
      networks:
        app_pathway_network:
        
    auth:
      container_name: app_auth
      build:
        dockerfile: pkg/user/auth/build/package/Dockerfile
        context: ../../../
      env_file:
        - env/auth.env   
      volumes:
        - $PKG/user/auth/cmd/server/main.go:$PKG/user/auth/main.go
        - $PKG/user/auth:$PKG/user/auth
        - $PKG/db_api:$PKG/db_api
        - $PKG/net:$PKG/net
        - $PKG/errors:$PKG/errors
        - $PKG/debug:$PKG/debug
        - $ROOT/secrets/crt/auth:/etc/ssl/certs/auth
        - $ROOT/secrets/crt/dgraph:/etc/ssl/certs/dgraph
      networks:
        app_pathway_network:

    auth_db_api:
        container_name: app_auth_db_api
        build:
          dockerfile: pkg/db_api/build/package/Dockerfile
          context: ../../../
        env_file:
          - env/auth.env   
        volumes:
          - $PKG/db_api/internals:/app/internals
          - $PKG/db_api/go.mod:/app/go.mod
          - $PKG/db_api/go.sum:/app/go.sum
          - $PKG/db_api/cmd/server/main.go:/app/main.go
          - $PKG/errors:$PKG/errors
        networks:
          app_pathway_network: