// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package intentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IntentClient is the client API for Intent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntentClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type intentClient struct {
	cc grpc.ClientConnInterface
}

func NewIntentClient(cc grpc.ClientConnInterface) IntentClient {
	return &intentClient{cc}
}

func (c *intentClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/intentpb.Intent/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntentServer is the server API for Intent service.
// All implementations should embed UnimplementedIntentServer
// for forward compatibility
type IntentServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedIntentServer should be embedded to have forward compatible implementations.
type UnimplementedIntentServer struct {
}

func (UnimplementedIntentServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

// UnsafeIntentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntentServer will
// result in compilation errors.
type UnsafeIntentServer interface {
	mustEmbedUnimplementedIntentServer()
}

func RegisterIntentServer(s grpc.ServiceRegistrar, srv IntentServer) {
	s.RegisterService(&Intent_ServiceDesc, srv)
}

func _Intent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntentServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/intentpb.Intent/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntentServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Intent_ServiceDesc is the grpc.ServiceDesc for Intent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Intent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intentpb.Intent",
	HandlerType: (*IntentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Intent_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "intent.proto",
}
